# Generated by Django 5.0.4 on 2024-05-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='playlists_acessadas',
            field=models.ManyToManyField(to='curso.playlist'),
        ),
    ]
