# Generated by Django 5.0.4 on 2024-05-29 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0006_alter_comentariospost_post_avaliacao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avaliacao',
        ),
    ]
